language: go

# must stay consistent with make/image.mk's GO_VERSION
go:
  - 1.12

env:
  - T=unit
  - T=integration KUBERNETES_VERSION=1.11
  - T=integration KUBERNETES_VERSION=1.12
  - T=integration KUBERNETES_VERSION=1.13
  - T=integration DEPLOY_METHOD=download
  - T=integration WITH_DEV_IMAGE=1
  - T=dry_run_deploy

install:
  - curl https://glide.sh/get | sh
  - cd $TRAVIS_BUILD_DIR/admission-webhook && glide install -v

cache:
  directories:
    # contains glide's cache
    - ~/.glide

script:
  - cd $TRAVIS_BUILD_DIR/admission-webhook && ./.travis.sh
